{
 "title": "ccfd",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Number Blocked Frauds",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\nFROM transaction \nWHERE \"Fraud\" = true AND \"Accepted\" = false"
    }
   ]
  },
  {
   "title": "Number Accepted Frauds",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\nFROM transaction \nWHERE \"Fraud\" = true AND \"Accepted\" = true"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*)\nFROM transaction"
    }
   ]
  },
  {
   "title": "Num transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT Count(*)\nFROM transaction\nWHERE $__timeFilter(\"Time\") "
    }
   ]
  },
  {
   "title": "Num frauds",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT Count(*)\nFROM transaction \nWHERE $__timeFilter(\"Time\") AND \"Fraud\" "
    }
   ]
  },
  {
   "title": "Percentage Fraudulent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  AVG(\"Fraud\"::int) AS fraud_fraction\nFROM transaction\n"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT Count(*) FROM transaction WHERE $__timeFilter(\"Time\") "
    }
   ]
  },
  {
   "title": "Lost money / day",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(\"Time\", '1d') AS time,\n  SUM(\"Amount\") AS lost_money\nFROM transaction\nWHERE $__timeFilter(\"Time\") AND \"Fraud\"\nGROUP BY 1\nORDER BY 1;\n"
    }
   ]
  },
  {
   "title": "Fraction fraudulent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(\"Time\", $__interval) AS time,\n  AVG(\"Fraud\"::int) AS fraud_fraction\nFROM transaction\nWHERE $__timeFilter(\"Time\")\nGROUP BY 1\nORDER BY 1;\n"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler=\"/randomint\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(\"Time\", $__interval) AS time,\n  COUNT(*) AS transaction_count\nFROM transaction\nWHERE $__timeFilter(\"Time\")\nGROUP BY 1\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Requests / min",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler=\"/randomint\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT \"Amount\", \"Time\" AS time\nFROM transaction\nWHERE $__timeFilter(\"Time\")\n"
    }
   ]
  },
  {
   "title": "Transaction Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(\"Time\", 1m) AS time,\n  COUNT(*) / 60 AS transaction_per_second\nFROM transaction\nWHERE $__timeFilter(\"Time\")\nGROUP BY 1\nORDER BY 1;\n"
    }
   ]
  },
  {
   "title": "Fraud Scenario",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  \"FraudScenario\",\n  COUNT(*) AS count\nFROM transaction\nWHERE \"Fraud\" AND $__timeFilter(\"Time\")\nGROUP BY \"FraudScenario\"\nORDER BY \"FraudScenario\""
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } }
 ]
}