services:
  postgres:
    container_name: postgres
    image: postgres
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
    healthcheck:
      test: pg_isready
      start_period: 10s
      start_interval: 1s
    ports:
      - 5432:5432

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    volumes:
      - ./grafana/grafana-provisioning:/etc/grafana/provisioning
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_SECURITY_ADMIN_PASSWORD: password
    ports:
      - 3000:3000

  ccfd_api:
    container_name: ccfd_api
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    build: ./ccfd_api
    image: ccfd_api
    restart: on-failure
    ports:
      - 8000:8000

  transaction_generator:
    container_name: transaction_generator
    build: ./transaction_generator
    image: transaction_generator
    depends_on:
      ccfd_api:
        condition: service_healthy
        restart: true