{
 "title": "ccfd",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Transaction Monitoring (via DB)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) as \"Transactions\"\nFROM transaction\nWHERE $__timeFilter(\"Time\") "
    },
    {
     "rawSql": "SELECT count(*) AS \"Blocked Genuine\"\nFROM transaction\nWHERE $__timeFilter(\"Time\") AND NOT \"Fraud\" AND NOT \"Accepted\""
    },
    {
     "rawSql": "SELECT count(*) AS \"Frauds\"\nFROM transaction\nWHERE $__timeFilter(\"Time\") AND \"Fraud\""
    },
    {
     "rawSql": "SELECT count(*) AS \"Accepted Frauds\"\nFROM transaction\nWHERE $__timeFilter(\"Time\") AND \"Fraud\" AND \"Accepted\""
    },
    {
     "rawSql": "SELECT count(*) AS \"Blocked Frauds\"\nFROM transaction\nWHERE $__timeFilter(\"Time\") AND \"Fraud\" AND NOT \"Accepted\""
    }
   ]
  },
  {
   "title": "Transaction Amount",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "rawSql": "SELECT \"Amount\" AS \"Genuine Amount\", \"Time\" AS time\nFROM transaction\nWHERE $__timeFilter(\"Time\") AND NOT \"Fraud\""
    },
    {
     "rawSql": "SELECT \"Amount\" AS \"Fraudulent Amount\", \"Time\" AS time\nFROM transaction\nWHERE $__timeFilter(\"Time\") AND \"Fraud\""
    }
   ]
  },
  {
   "title": "Transaction Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(\"Time\", '1s') AS time,\n  COUNT(*) AS \"Genuine\"\nFROM transaction\nWHERE $__timeFilter(\"Time\") AND NOT \"Fraud\"\nGROUP BY 1\nORDER BY 1;"
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(\"Time\", '1s') AS time,\n  COUNT(*) AS \"Fraudulent\"\nFROM transaction\nWHERE $__timeFilter(\"Time\") AND \"Fraud\"\nGROUP BY 1\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Recent Transactions",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT \"Time\", \"Amount\", \"Accepted\", \"Fraud\", \"FraudScenario\", \"CustomerID\", \"TerminalID\" FROM transaction\nWHERE $__timeFilter(\"Time\") \nORDER BY \"Time\" DESC"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(handler) (rate(http_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(handler) (rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[15s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Classifier", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Decision Tree (Now)",
   "type": "text",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 30 },
   "options": {
    "content": "<img src=\"/api/datasources/proxy/uid/json-api/fraud_detection/tree/visualize?t=${__from}\"\n"
   }
  },
  {
   "title": "Classification Performance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(\"Time\", '15s') AS time,\n  COUNT(*) FILTER (WHERE NOT \"Fraud\" AND \"Accepted\")::float / NULLIF(COUNT(*) FILTER (WHERE NOT \"Fraud\"), 0) AS \"Genuine True\",\n  COUNT(*) FILTER (WHERE NOT \"Fraud\" AND NOT \"Accepted\")::float / NULLIF(COUNT(*) FILTER (WHERE NOT \"Fraud\"), 0) AS \"Genuine False\",\n  COUNT(*) FILTER (WHERE \"Fraud\" AND NOT \"Accepted\")::float / NULLIF(COUNT(*) FILTER (WHERE \"Fraud\"), 0) AS \"Fraud True\",\n  COUNT(*) FILTER (WHERE \"Fraud\" AND \"Accepted\")::float / NULLIF(COUNT(*) FILTER (WHERE \"Fraud\"), 0) AS \"Fraud False\"\nFROM transaction\nWHERE $__timeFilter(\"Time\")\nGROUP BY 1\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Feature Importance",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "avg by(feature_name) (rate(feature_importance_sum[1m]) / rate(feature_importance_count[1m]))",
     "legendFormat": "{{feature_name}}"
    }
   ]
  },
  {
   "title": "Training Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(job) (rate(model_training_duration_seconds_sum[1m]) / rate(model_training_duration_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Database Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Query Mean Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    { "expr": "pg_stat_statements_mean_time", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Query Total Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "targets": [
    { "expr": "pg_stat_statements_total_time", "legendFormat": "__auto" }
   ]
  }
 ]
}