name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - dev
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [ccfd-api, transaction-generator] 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: charlotteknight/${{ matrix.service }}
          tags: |
            # Branches
            type=ref,event=branch
            # Git tags (v1.2.3 → 1.2.3)
            type=semver,pattern={{version}}
            # Commit SHA
            type=sha
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}

          flavor: |
            latest=auto   # Assign :latest if it's main branch or highest semver

      - name: Build and push ${{ matrix.service }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.service }}
          file: ${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=charlotteknight/${{ matrix.service }}:buildcache
          cache-to: type=registry,ref=charlotteknight/${{ matrix.service }}:buildcache,mode=max

